---
- hosts: localhost
  gather_facts: no

  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    parent_folder: "1.Internal-Training/Students"
    esxi_username: "root"
    esxi_password: "VMware1!"
    public_net:  "DPG-172.0.10.x"
    datastore_name: "vsanDatastore"
    templateJumpbox: "Temp-Jumpbox"
    templateRHEL: "Temp-RHEL" 
    templateRocky: "Temp-Rocky" 
    templatePhoton: "Temp-Photon"
    templateUbuntu: "Temp-Ubuntu" 
    snapShotName: "Prepared"

    SID_ESXi: 
    - { id: S00, host: 172.0.10.13 }
    - { id: S01, host: 172.0.10.11 }
    - { id: S02, host: 172.0.10.12 }
    - { id: S03, host: 172.0.10.13 }
    - { id: S04, host: 172.0.10.11 }
    - { id: S05, host: 172.0.10.12 }
    - { id: S06, host: 172.0.10.13 }
    - { id: S07, host: 172.0.10.11 }
    - { id: S08, host: 172.0.10.12 }
    - { id: S09, host: 172.0.10.13 }
    - { id: S10, host: 172.0.10.11 }
    - { id: S11, host: 172.0.10.12 }
    - { id: S12, host: 172.0.10.13 }
    - { id: S13, host: 172.0.10.11 }
    - { id: S14, host: 172.0.10.12 }


  tasks: 
  - name: 01. Create a Project folder
    community.vmware.vcenter_folder:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      datacenter_name: '{{ datacenter_name }}'
      folder_name: '{{ item.id }}'
      parent_folder: '{{ parent_folder }}'
      state: present
    loop: "{{ SID_ESXi }}"  
    register: sub_folder_creation_result
    delegate_to: localhost


  - name: 02. Create Project Standard vSwitch
    community.vmware.vmware_vswitch:
      hostname: '{{ item.host }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      validate_certs: false
      switch: '{{ item.id }}'
    loop: "{{ SID_ESXi }}"  
    delegate_to: localhost


  - name: 03. waiting vswitch creating
    wait_for:
      timeout: 10
    delegate_to: localhost


  - name: 04. Adding Portgroups to LAB Switch
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ item.host }}"
      validate_certs: no
      switch: "{{ item.id }}"
      portgroup: "{{ item.id + '-Internal' }}"
    loop: "{{ SID_ESXi }}"      
    delegate_to: localhost


  - name: 05. Deploy Jumpbox for LAB
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id + '-Jumpbox' }}"
      state: "poweredoff"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ datacenter_name + '/vm/' + parent_folder + '/' + item.id }}"
      esxi_hostname: '{{ item.host }}'
      datastore: "{{ datastore_name }}"
      template: "{{ templateJumpbox }}"
      linked_clone: True
      snapshot_src: "{{ snapShotName }}"
    loop: "{{ SID_ESXi }}"  
    delegate_to: localhost


  - name: 06.Change Jumpbox Network
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      name: "{{ item.id + '-Jumpbox' }}"
      network_name: "{{ item.id + '-Internal' }}"
      label: "Network adapter 2"
      state: present
    loop: "{{ SID_ESXi }}"
    delegate_to: localhost


  - name: 07.Poweron Jumpbox VM
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id + '-Jumpbox' }}"
      state: "poweredon"
    loop: "{{ SID_ESXi }}"        
    delegate_to: localhost


  - name: 08. Deploy RHEL VM for LAB
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id + '-RHEL' }}"
      state: "poweredoff"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ datacenter_name + '/vm/' + parent_folder + '/' + item.id }}"
      esxi_hostname: '{{ item.host }}'
      datastore: "{{ datastore_name }}"
      template: "{{ templateRHEL }}"
    loop: "{{ SID_ESXi }}"  
    delegate_to: localhost


  - name: 09.Change RHEL VM Network
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      name: "{{ item.id + '-RHEL' }}"
      network_name: "{{ item.id + '-Internal' }}"
      label: "Network adapter 1"
      state: present
    loop: "{{ SID_ESXi }}"
    delegate_to: localhost

  - name: 10. Deploy Rocky VM for LAB
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id + '-Rocky' }}"
      state: "poweredoff"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ datacenter_name + '/vm/' + parent_folder + '/' + item.id }}"
      esxi_hostname: '{{ item.host }}'
      datastore: "{{ datastore_name }}"
      template: "{{ templateRocky }}"
    loop: "{{ SID_ESXi }}"  
    delegate_to: localhost


  - name: 11.Change Rocky VM Network
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      name: "{{ item.id + '-Rocky' }}"
      network_name: "{{ item.id + '-Internal' }}"
      label: "Network adapter 1"
      state: present
    loop: "{{ SID_ESXi }}"
    delegate_to: localhost

  - name: 12. Deploy Photon VM for LAB
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id + '-Photon' }}"
      state: "poweredoff"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ datacenter_name + '/vm/' + parent_folder + '/' + item.id }}"
      esxi_hostname: '{{ item.host }}'
      datastore: "{{ datastore_name }}"
      template: "{{ templatePhoton }}"
    loop: "{{ SID_ESXi }}"  
    delegate_to: localhost


  - name: 13.Change Photon VM Network
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      name: "{{ item.id + '-Photon' }}"
      network_name: "{{ item.id + '-Internal' }}"
      label: "Network adapter 1"
      state: present
    loop: "{{ SID_ESXi }}"
    delegate_to: localhost

  - name: 14. Deploy Ubuntu VM for LAB
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id + '-Ubuntu' }}"
      state: "poweredoff"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ datacenter_name + '/vm/' + parent_folder + '/' + item.id }}"
      esxi_hostname: '{{ item.host }}'
      datastore: "{{ datastore_name }}"
      template: "{{ templateUbuntu }}"
    loop: "{{ SID_ESXi }}"  
    delegate_to: localhost


  - name: 15.Change Ubuntu VM Network
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      name: "{{ item.id + '-Ubuntu' }}"
      network_name: "{{ item.id + '-Internal' }}"
      label: "Network adapter 1"
      state: present
    loop: "{{ SID_ESXi }}"
    delegate_to: localhost
